### ISSUE TITLE
Renewal error 

### ISSUE THREAD

**Issue by Beastshubh** [Klovit/KlovitClient#18]
![Screenshot_2023-10-21-17-38-06-59_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Klovit/KlovitClient/assets/117744152/0c175f12-6616-4b4c-b9bc-1f78cddad038)
When i enable renew

**Comment by BeastGamer81** [comment]
Fixed in the latest [Commit.](https://github.com/Klovit/KlovitClient/commit/2c86f79ac8d321974462063de84c1ba2d7a697ac)
