### ISSUE TITLE
Linkvertise generate button error 

### ISSUE THREAD

**Issue by Beastshubh** [Klovit/KlovitClient#19]
![Screenshot_2023-10-22-11-34-32-48_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Klovit/KlovitClient/assets/117744152/36e74cb7-a36a-4032-b20c-1486bee468bd)
When i click on Linkvertise generate button i am getting this

**Comment by BeastGamer81** [comment]
Fixed in the latest commit
