### ISSUE TITLE
Refresh account data error 

### ISSUE THREAD

**Issue by Beastshubh** [Klovit/KlovitClient#20]
![Screenshot_2023-10-22-11-36-46-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Klovit/KlovitClient/assets/117744152/58a0d563-6e22-45d7-a964-14e94f93b363)
When i click on refresh account data i get this

**Comment by BeastGamer81** [comment]
Logs please

**Comment by Beastshubh** [comment]
Ok providing wait

**Comment by Beastshubh** [comment]
![Screenshot_2023-10-23-13-50-55-55_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Klovit/KlovitClient/assets/117744152/ce71397f-fb12-4527-8c9d-bea5a46bbcdc)

**Comment by BeastGamer81** [comment]
Fixed in the latest commit, please update your KlovitClient V0.3 instance
