### ISSUE TITLE
Server modify error 

### ISSUE THREAD

**Issue by Beastshubh** [Klovit/KlovitClient#23]
![Screenshot_2023-10-23-20-36-56-81_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Klovit/KlovitClient/assets/117744152/fb2b76b9-999c-408d-988a-d40440fc6177)
Error while modifying resources of Server

**Comment by BeastGamer81** [comment]
Logs

**Comment by Beastshubh** [comment]
Fixed
