### ISSUE TITLE
Linkvertise reward error 

### ISSUE THREAD

**Issue by Beastshubh** [Klovit/KlovitClient#24]
![Screenshot_2023-10-24-21-02-31-71_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Klovit/KlovitClient/assets/117744152/2daa22d7-f474-4879-9788-68e1db5d056e)
After completing linkvertise links user didn't get any reward getting this error

**Comment by BeastGamer81** [comment]
You have broken the License terms and we don't give to support who has broken our License terms.
