### ISSUE TITLE
UI messed up

### ISSUE THREAD

**Issue by Sobble2546** [Klovit/KlovitClient#33]
![image](https://github.com/Klovit/KlovitClient/assets/89291105/de4865ac-1066-4c26-bd67-07d524407521)
UI is glitching

**Comment by Sobble2546** [comment]
sadly i am a user of the service so cant send log

**Comment by Sobble2546** [comment]
![image](https://github.com/Klovit/KlovitClient/assets/89291105/d94b555a-934f-4c13-8d09-6ef489e3e53a)
![image](https://github.com/Klovit/KlovitClient/assets/89291105/2b0b1887-a763-43a1-a663-ef9e58a14529)
couldn't find the issue tab :skull:

**Comment by BeastGamer81** [comment]
Do you know that I only give partial support to V0.4?

**Comment by Sobble2546** [comment]
nah

**Comment by privt00** [comment]
It looks bruh

**Comment by BeastGamer81** [comment]
V0.5 is released.
