### ISSUE TITLE
index.js not found

### ISSUE THREAD

**Issue by Luchs3-tech** [Klovit/KlovitClient#38]
When I try to start KlovitClient I get the message that the script cannot be found.
I also tried re-cloning it from Github without success.

`pm2 start ./dist/index.js --name KlovitClient
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized`
`[PM2][ERROR] Script not found: /home/KlovitClient/dist/index.js`

System: Debian

**Comment by zebronixllc** [comment]
./dist/index.js does not exist when we build up the client cuz dark is brainded

**Comment by zebronixllc** [comment]
pm2 uff

**Comment by BeastGamer81** [comment]
Run `pm2 start ./dist/server/entry.mjs --name KlovitClient`
