### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by arkseek** [Klovit/KlovitClient#41]
Hello! I don't have an issue but I got a question, I am currently a beginner programmer and looking for projects to contribute to. is there any way I can contribute to KlovitClient?

**Comment by BeastGamer81** [comment]
Yes, you can help us in the UI and the Documentation.

**Comment by arkseek** [comment]
Hey, thanks for replying! is there any form we can communicate in discord? if so please add me: hamz.ah

**Comment by BeastGamer81** [comment]
Yes, we can communicate through Discord. My username is - darknight81
